@startuml
title Теплый дом. С4 диаграмма контекста

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Клиент")

System(MainSystem, "Монолит", "Управление взаимодействием с датчиками")
SystemQueue(Sensor, "Датчик", "Замер температуры")

Rel(user, MainSystem, "Регулирование температуры")
Rel(Sensor, MainSystem, "Обработка команд")
@enduml