openapi: 3.1.0
info:
  title: Умный дом
  description: REST-API спецификация системы умный дом
  version: 1.0.0
servers:
  - url: 'https:localhost:8081'
tags:
  - name: device
    description: взаимодействие с датчиками и камерами
  - name: house
    description: Регистрирует устройства
  - name: user
    description: Создание, редактирование, изменение прав
paths:
  /device/add:
    post:
      tags:
        - device
      summary: Регистрация нового устройства.
      description: Активация при первичной настройке.
      operationId: addDevice
      requestBody:
        content:
          application/json:
            schema:
              properties:
                serialNumber:
                  type: string
                typeId:
                  type: integer
                houseId:
                  type: integer
      responses:
        '200':
          description: Device activated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/device'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
        default:
          description: Unexpected error

  /device/{deviceId}:
    get:
      tags:
        - device
      summary: Получить устройство по идентификатору
      description: Возвращает информацию о устройстве
      operationId: getDeviceById
      parameters:
        - name: deviceId
          in: path
          description: ID of device to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/device'
        '400':
          description: Invalid ID supplied
        '404':
          description: device not found
        default:
          description: Unexpected error

  /device/{deviceId}/getStatus:
    get:
      tags:
        - device
      summary: Получить текущий статус устройства
      description: Включено/выключено
      operationId: getDeviceStatusById
      parameters:
        - name: deviceId
          in: path
          description: ID of device to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deviceStatus'
        '400':
          description: Invalid ID supplied
        '404':
          description: device not found
        default:
          description: Unexpected error

      security:
        - api_key: [ ]

  /device/{deviceId}/runCommand:
    post:
      tags:
        - device
      summary: Отправка команды на устройство
      description: Выполнение команды
      operationId: runCommand
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: integer
                command:
                  type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deviceCommand'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
        default:
          description: Unexpected error

  /user/{userId}:
    get:
      tags:
        - user
      summary: Получить устройство по идентификатору
      description: Возвращает информацию о пользователе
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '400':
          description: Invalid ID supplied
        '404':
          description: user not found
        default:
          description: Unexpected error

  /house/{houseId}:
    get:
      tags:
        - house
      summary: Получить информацию о доме по идентификатору
      description: Возвращает информацию о доме
      operationId: getHouseById
      parameters:
        - name: houseId
          in: path
          description: ID of house to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/house'
        '400':
          description: Invalid ID supplied
        '404':
          description: house not found
        default:
          description: Unexpected error

components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [10]
        name:
          type: string
          examples: [Ivanov Ivan Ivanovich]
        email:
          type: string
          examples: [john@email.com]
        passwordHash:
          type: string
          examples: ['0afbce0204d4331eb20f9c58c0a424411e5403c8']
        isActive:
          type: boolean
          examples: [ true ]
        isDeleted:
          type: boolean
          examples: [ false ]

    deviceType:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [ 10 ]
        type:
          type: string
          examples: [ camera, water_sensor, fire_sensor ]
    device:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [10]
        typeId:
          type: integer
          examples: [1]
        serialNumber:
          type: string
          description: Unique serial number of device
          examples: [C02G801QMD6M]
        activatedDate:
          type: string
          description: Date of device activated
          examples: ['2026-10-10 00:00:00']
        deactivatedDate:
          type: string
          description: Date of device deactivated
          examples: [ '2026-10-11 00:00:00' ]
        houseId:
          type: integer
          examples: [ 1 ]
        isActive:
          type: boolean
          examples: [ true ]
    deviceStatus:
      required:
        - deviceId
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [10]
        status:
          type: string
          description: device status in the store
          enum:
            - enabled
            - disabled
    deviceCommand:
      required:
        - deviceId
        - command
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [ 10 ]
        status:
          type: string
          description: command run status
          enum:
            - success
            - failed
        error_msg:
          type: string
          description: error message if exists
          examples: ['NULL','Device not exists']
    house:
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [ 10 ]
        name:
          type: string
          examples: [ Ivanov Ivan Ivanovich's house ]
        location:
          type: string
          examples: [ '55.703056, 37.530278' ]
        isActive:
          type: boolean
          examples: [ true ]
